language: java
env:
  global:
  - secure: SQNV05R5rzwx2d9GLABnKdfnHEXCvdjAzfWrWgXyzVxhLBlpb4wN/vxP8K8tmt9rksRgGQPcwUY3l4T0JKcKTLdckyhO4IRBCCrTdS98b5Eyk2cd419NZiy7ZAjHqEPxmtPuCFjHQPWoiDBJ3A0OE9mrDnHmKtL0/sJjSggDVUUmNfd/n+vGBw8XPneVgV9glh8CVR71Kur+vli+AS5L1qddebWYamjfBlD0IYUF1w5eOnWeB2g2w/KnYdG3MgMcAtKnwYjBJ5NY9zLrsB+EKUCl6TmYW8CgbVRxaYxUlsdQGlMRL7oy7px4SCQw3ngrkOVV/iUFGruIGz+c0qHZOrMR4/LaWJn8mZKPP/+d84jPlUmy1Gr0fozEpEY9f3R/a3BHpmeLO4bSTT+jX8Tw9XZoiVP74nRkVY1f9P8gYkR/fks/ATxZPT88VOVmCTV+UG1TN4Vv389Esb3XK2YUCwnkAC+reeyRW8qQdSBeP7RRZHL3eOKX2K/w+5I2K6hO9alCAWEgmrdI4kDCE68tslpgpMuzNGqtksCWpWqP52Cz2QuRCGMoAuTbT2L9jNkJ9z/pDoXgJw+pw8SaXFfvTW40zFIpMlha5GB4teVNxJpY49OcCvsclbA6y0oRTXL/5HtjcaDPZ3vAmvqtFul3N2KJIjgtxCp4NwSmzfSymNw=
  - secure: paVWmaWdcsQmXqZWadaIIAgxOM1dhULDQ0iz1H2J6rCGT7DyZkETGpFgdp6oRc7pFIUUh7XPtVIF8YNht7CfLCUyvN4HfUdYeJ8NqV/qrQ5TqliIkdkceCLNKaKrmi4w6E7b1HnnBQMeuoNvQj8+u1POtcvK4Urci8w61aaDbMMZN81/sq8k+8yxLgG20jBwodLiTryOXqNWu4PfN/P0jxmu4u42KpJU0sKb2evZ6nf8SqEUII/Zod4YY1rLgd9U9MTymk396GJLIQIVLzanIyf6/bk3XQ65aJ/PTekSlXVukThsUgAUFFzKvrzwk74ytLWepHeHFR9ZRiIF3iQys2ZUgSiBSToKuXd3YDkd2kggTxozkqWy1/6jL7YkBnSNH4ZsoXZu+nOJy3QId7x845JQe8BCFP+BlFEuw+6diD+yCL89E0q4SUcM5DKQwUTFolroth3PgploqOIYgrzHF0O6M+irVvXxkOYUj02R38nuf3dvK+pgrsN/QDuwMRvm2QSaUs5VFZORxQUdxFVll8vw3wjhqBLGKTR6OuAiEb3TO5ChJaWhJ9DjGTongRJ4AnK043RlHIT4cc4jjh0egZHFzf5aeVOw9R2WXXcmgrLSjolZ7J/4hXrdFb8TN2hOipUnAfjK6beninDnLnVis6mQNKMt+PjacVTkrx1Sp3Y=

addons:
  sonarcloud:
    organization: "fabio00158"
    token:
      secure: SOMEVAR

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar